//! JSON Schema → GBNF compiler (v0.1).
//!
//! Compiles a per-method args schema into a GBNF sub-grammar that, in v0.5,
//! the I/O daemon swaps in for the generic `json` rule when the model is
//! about to emit `<|call|>cart.method` args. This eliminates the
//! schema-violation retry path on the happy path (refinement §1.4 +
//! design §3.2).
//!
//! Subset supported in v0.1 (covers every shipped cartridge schema):
//! - `type: object` with `required` (required props emitted in declaration
//!   order; optional props ignored in the strict form).
//! - `type: array` with `items`. `minItems`/`maxItems` honored for small
//!   bounds (we unroll up to maxItems=10; larger arrays get the unbounded
//!   form).
//! - `type: string` with `enum` → quoted-string alternation. Plain strings
//!   become a generic string rule.
//! - `type: integer` / `type: number` — generic numeric rule (range
//!   constraints not enforceable in pure GBNF; documented in the emitted
//!   header comment so v0.5 can layer logit-bias filtering on top).
//! - `type: boolean` → `"true" | "false"`.
//! - `enum` of mixed scalars → literal alternation.
//! - `$ref` to local `#/definitions/<name>` and `#/$defs/<name>`.
//!
//! Out of scope for v0.1 (handled at runtime via the existing
//! `jsonschema` crate validator):
//! - `pattern`, `format`, `additionalProperties` enforcement, `oneOf`,
//!   `allOf`, `anyOf`, `if/then/else`, numeric range constraints.

use serde_json::Value;
use std::collections::BTreeMap;

#[derive(Debug, thiserror::Error)]
pub enum CompileError {
    #[error("unsupported schema construct: {0}")]
    Unsupported(String),
    #[error("malformed schema: {0}")]
    Malformed(String),
    #[error("ref resolution failed: {0}")]
    RefResolve(String),
}

/// Compile a JSON Schema into a complete GBNF document.
///
/// `root_name` becomes the top-level rule name (will be sanitized to GBNF's
/// `[a-z0-9_-]+` form). Boilerplate (whitespace, generic JSON primitives)
/// is appended to the output so the result is self-contained.
pub fn compile(schema: &Value, root_name: &str) -> Result<String, CompileError> {
    let mut c = Compiler::new(schema);
    let root_rule = sanitize(root_name);
    let body = c.emit(schema, &root_rule)?;
    if body != root_rule {
        // Top-level node was a reference — alias root.
        c.add_rule(&root_rule, &body);
    }
    Ok(c.finish(&root_rule))
}

fn sanitize(name: &str) -> String {
    let mut out = String::new();
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' || ch == '-' {
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push('-');
        }
    }
    if out.is_empty() {
        "rule".into()
    } else {
        out
    }
}

struct Compiler<'a> {
    schema_root: &'a Value,
    /// Rules emitted in insertion order.
    rules: BTreeMap<String, String>,
    counter: usize,
    needs_string: bool,
    needs_number: bool,
    needs_boolean: bool,
    needs_ws: bool,
}

impl<'a> Compiler<'a> {
    fn new(root: &'a Value) -> Self {
        Self {
            schema_root: root,
            rules: BTreeMap::new(),
            counter: 0,
            needs_string: false,
            needs_number: false,
            needs_boolean: false,
            needs_ws: false,
        }
    }

    fn add_rule(&mut self, name: &str, body: &str) {
        self.rules.insert(name.to_string(), body.to_string());
    }

    fn fresh(&mut self, hint: &str) -> String {
        self.counter += 1;
        format!("{hint}-{}", self.counter)
    }

    fn finish(self, root_name: &str) -> String {
        let mut out = String::new();
        out.push_str("# Auto-generated by runtime/schema_to_gbnf.rs — do not edit.\n");
        out.push_str("# v0.1 subset: object/array/string/number/integer/boolean/enum/$ref.\n");
        out.push_str("# Numeric range constraints are not enforced (GBNF can't); v0.5\n");
        out.push_str("# layers logit-bias filtering on top.\n\n");
        out.push_str(&format!("root ::= {root_name}\n\n"));
        for (name, body) in &self.rules {
            out.push_str(&format!("{name} ::= {body}\n"));
        }
        out.push('\n');
        if self.needs_ws {
            out.push_str("ws ::= [ \\t\\n]*\n");
        }
        if self.needs_string {
            out.push_str("string ::= \"\\\"\" string-char* \"\\\"\"\n");
            out.push_str("string-char ::= [^\"\\\\\\x7F\\x00-\\x1F] | \"\\\\\" [\"\\\\bfnrt/]\n");
        }
        if self.needs_number {
            out.push_str("number ::= \"-\"? [0-9]+ ( \".\" [0-9]+ )? ( [eE] [-+]? [0-9]+ )?\n");
        }
        if self.needs_boolean {
            out.push_str("boolean ::= \"true\" | \"false\"\n");
        }
        out
    }

    fn emit(&mut self, node: &Value, suggested: &str) -> Result<String, CompileError> {
        // Resolve $ref before anything else.
        if let Some(reference) = node.get("$ref").and_then(Value::as_str) {
            return self.emit_ref(reference);
        }

        // Top-level enum collapses regardless of `type`.
        if let Some(enum_vals) = node.get("enum").and_then(Value::as_array) {
            return self.emit_enum(enum_vals, suggested);
        }
        if let Some(constant) = node.get("const") {
            return self.emit_enum(&[constant.clone()], suggested);
        }

        let ty = node
            .get("type")
            .and_then(Value::as_str)
            .ok_or_else(|| CompileError::Malformed("missing 'type' and no enum/const".into()))?;

        match ty {
            "object" => self.emit_object(node, suggested),
            "array" => self.emit_array(node, suggested),
            "string" => {
                self.needs_string = true;
                Ok("string".into())
            }
            "integer" | "number" => {
                self.needs_number = true;
                Ok("number".into())
            }
            "boolean" => {
                self.needs_boolean = true;
                Ok("boolean".into())
            }
            "null" => Ok("\"null\"".into()),
            other => Err(CompileError::Unsupported(format!("type='{other}'"))),
        }
    }

    fn emit_ref(&mut self, reference: &str) -> Result<String, CompileError> {
        // Support local refs: #/definitions/<name> or #/$defs/<name>
        let stripped = reference
            .strip_prefix("#/definitions/")
            .or_else(|| reference.strip_prefix("#/$defs/"))
            .ok_or_else(|| {
                CompileError::Unsupported(format!("non-local $ref: {reference}"))
            })?;
        let target = self
            .schema_root
            .get("definitions")
            .and_then(|d| d.get(stripped))
            .or_else(|| {
                self.schema_root
                    .get("$defs")
                    .and_then(|d| d.get(stripped))
            })
            .ok_or_else(|| CompileError::RefResolve(reference.to_string()))?
            .clone();
        let rule_name = sanitize(stripped);
        if !self.rules.contains_key(&rule_name) {
            // Insert a placeholder to handle direct cycles.
            self.add_rule(&rule_name, "/* placeholder */");
            let body = self.emit(&target, &rule_name)?;
            self.add_rule(&rule_name, &body);
        }
        Ok(rule_name)
    }

    fn emit_enum(&mut self, vals: &[Value], suggested: &str) -> Result<String, CompileError> {
        let mut alts = Vec::with_capacity(vals.len());
        for v in vals {
            alts.push(literal_for(v));
        }
        if alts.is_empty() {
            return Err(CompileError::Malformed("enum is empty".into()));
        }
        let body = alts.join(" | ");
        if alts.len() == 1 {
            return Ok(body);
        }
        let name = self.fresh(&format!("{suggested}-enum"));
        self.add_rule(&name, &format!("({body})"));
        Ok(name)
    }

    fn emit_object(
        &mut self,
        node: &Value,
        suggested: &str,
    ) -> Result<String, CompileError> {
        self.needs_ws = true;
        let props = node
            .get("properties")
            .and_then(Value::as_object)
            .cloned()
            .unwrap_or_default();
        let required: Vec<String> = node
            .get("required")
            .and_then(Value::as_array)
            .map(|a| {
                a.iter()
                    .filter_map(|v| v.as_str().map(String::from))
                    .collect()
            })
            .unwrap_or_default();

        if required.is_empty() {
            // Object with no required fields → permissive empty object.
            // We don't enumerate optional properties; the model can emit
            // an empty `{}`. This is the v0.1 strict-form trade-off.
            return Ok("\"{}\"".into());
        }

        let mut kv_chunks = Vec::with_capacity(required.len());
        for key in &required {
            let prop_schema = props.get(key).ok_or_else(|| {
                CompileError::Malformed(format!(
                    "required property '{key}' missing from properties"
                ))
            })?;
            let value_rule = self.emit(prop_schema, &format!("{suggested}-{key}"))?;
            kv_chunks.push(format!(
                "\"\\\"{key}\\\":\" ws {value_rule}"
            ));
        }
        let body = format!(
            "\"{{\" ws {first} {rest} ws \"}}\"",
            first = kv_chunks[0],
            rest = kv_chunks[1..]
                .iter()
                .map(|c| format!("ws \",\" ws {c}"))
                .collect::<Vec<_>>()
                .join(" ")
        );
        let name = self.fresh(suggested);
        self.add_rule(&name, &body);
        Ok(name)
    }

    fn emit_array(&mut self, node: &Value, suggested: &str) -> Result<String, CompileError> {
        self.needs_ws = true;
        let items = node
            .get("items")
            .ok_or_else(|| CompileError::Malformed("array missing 'items'".into()))?;
        let item_rule = self.emit(items, &format!("{suggested}-item"))?;
        let min_items = node
            .get("minItems")
            .and_then(Value::as_u64)
            .unwrap_or(0);
        let max_items = node.get("maxItems").and_then(Value::as_u64);

        // If both min and max are equal and small, unroll.
        if let Some(max) = max_items {
            if min_items == max && max > 0 && max <= 10 {
                let pieces = (0..max)
                    .map(|i| {
                        if i == 0 {
                            item_rule.clone()
                        } else {
                            format!("ws \",\" ws {item_rule}")
                        }
                    })
                    .collect::<Vec<_>>()
                    .join(" ");
                let body = format!("\"[\" ws {pieces} ws \"]\"");
                let name = self.fresh(suggested);
                self.add_rule(&name, &body);
                return Ok(name);
            }
        }

        let body = if min_items >= 1 {
            format!(
                "\"[\" ws {item_rule} (ws \",\" ws {item_rule})* ws \"]\""
            )
        } else {
            format!(
                "\"[\" ws ({item_rule} (ws \",\" ws {item_rule})*)? ws \"]\""
            )
        };
        let name = self.fresh(suggested);
        self.add_rule(&name, &body);
        Ok(name)
    }
}

fn literal_for(v: &Value) -> String {
    match v {
        Value::String(s) => format!("\"\\\"{s}\\\"\""),
        Value::Number(n) => format!("\"{n}\""),
        Value::Bool(b) => format!("\"{b}\""),
        Value::Null => "\"null\"".to_string(),
        // Object/array literals as enum members are rare; emit a JSON
        // string of them. v0.5 may want to emit structurally.
        other => format!("\"{}\"", serde_json::to_string(other).unwrap_or_default()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn compile_or_panic(s: &Value, name: &str) -> String {
        compile(s, name).expect("compile")
    }

    #[test]
    fn object_with_required_string_and_int() {
        let s = json!({
            "type": "object",
            "required": ["text", "count"],
            "properties": {
                "text":  {"type": "string"},
                "count": {"type": "integer"}
            }
        });
        let g = compile_or_panic(&s, "echo-args");
        assert!(g.contains("root ::= echo-args"));
        assert!(g.contains("\\\"text\\\""));
        assert!(g.contains("\\\"count\\\""));
        assert!(g.contains("string ::="));
        assert!(g.contains("number ::="));
    }

    #[test]
    fn enum_string_collapses_to_alternation() {
        let s = json!({
            "type": "string",
            "enum": ["north", "east", "south", "west"]
        });
        let g = compile_or_panic(&s, "dir");
        assert!(g.contains("\"\\\"north\\\"\" | \"\\\"east\\\"\" | \"\\\"south\\\"\" | \"\\\"west\\\"\""));
    }

    #[test]
    fn ref_to_definitions_resolves() {
        let s = json!({
            "type": "object",
            "required": ["d"],
            "properties": {
                "d": {"$ref": "#/definitions/aisle"}
            },
            "definitions": {
                "aisle": {"type": "array", "items": {"type": "string"}}
            }
        });
        let g = compile_or_panic(&s, "shopping");
        assert!(g.contains("aisle ::="));
    }

    #[test]
    fn boolean_emits_true_false_alt() {
        let s = json!({"type": "boolean"});
        let g = compile_or_panic(&s, "b");
        assert!(g.contains("boolean ::= \"true\" | \"false\""));
    }

    #[test]
    fn array_with_min_max_equal_unrolls() {
        let s = json!({
            "type": "array",
            "minItems": 3,
            "maxItems": 3,
            "items": {"type": "integer"}
        });
        let g = compile_or_panic(&s, "triple");
        // Should contain the item rule three times in sequence.
        let count = g.matches("number").count();
        // 1 occurrence in the rule definition + 3 inline references.
        assert!(count >= 4, "expected at least 4 'number' refs, got {count} in {g}");
    }

    #[test]
    fn const_emits_single_literal() {
        let s = json!({"const": "IEC_60364"});
        let g = compile_or_panic(&s, "code");
        assert!(g.contains("\"\\\"IEC_60364\\\"\""));
    }

    #[test]
    fn object_with_no_required_emits_empty_object_literal() {
        let s = json!({"type": "object", "additionalProperties": false});
        let g = compile_or_panic(&s, "empty");
        assert!(g.contains("\"{}\""));
    }

    #[test]
    fn nested_object_compiles() {
        let s = json!({
            "type": "object",
            "required": ["motion"],
            "properties": {
                "motion": {
                    "type": "object",
                    "required": ["left", "right"],
                    "properties": {
                        "left": {"type": "integer"},
                        "right": {"type": "integer"}
                    }
                }
            }
        });
        let g = compile_or_panic(&s, "outer");
        assert!(g.contains("\\\"motion\\\""));
        assert!(g.contains("\\\"left\\\""));
        assert!(g.contains("\\\"right\\\""));
    }
}
