#!/usr/bin/env bash
# T1 — Tokenizer parity sanity check + single-token validation.
#
# Two modes:
#   1. Report mode (default): generates docs/tokenization-report.md comparing
#      token counts across Qwen and Gemma vocab GGUFs.
#   2. Validate mode (--model <path>): checks that every ISA opcode tokenizes
#      to exactly 1 token in the given model. Exits non-zero on failure.
#      This is the CI gate for fine-tuned kernels.
#
# Usage:
#   # Generate report (development):
#   bash scripts/check_tokenizer.sh
#
#   # Validate fine-tuned model (CI):
#   bash scripts/check_tokenizer.sh --model ~/models/qwen-2.5-3b-llmos-v1.gguf
#
# Exit codes:
#   0  — report written / all tokens pass validation.
#   1  — validation failed (one or more tokens are multi-token).
#   2  — tokenize binary missing or vocabs missing.

set -u

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LLAMA_DIR="$ROOT/../llama.cpp"
REPORT="$ROOT/docs/tokenization-report.md"

# Parse arguments
VALIDATE_MODEL=""
while [[ $# -gt 0 ]]; do
  case $1 in
    --model)
      VALIDATE_MODEL="$2"
      shift 2
      ;;
    *)
      echo "Usage: $0 [--model <path-to-gguf>]" >&2
      exit 2
      ;;
  esac
done

# Find tokenize binary.
TOKENIZE=""
if command -v llama-tokenize >/dev/null 2>&1; then
  TOKENIZE="llama-tokenize"
else
  for cand in \
    "$LLAMA_DIR/build/bin/llama-tokenize" \
    "$LLAMA_DIR/build/bin/Release/llama-tokenize.exe" \
    "$LLAMA_DIR/build/bin/llama-tokenize.exe"; do
    if [ -x "$cand" ] || [ -f "$cand" ]; then
      TOKENIZE="$cand"
      break
    fi
  done
fi

if [ -z "$TOKENIZE" ]; then
  echo "error: llama-tokenize not found. Build with:" >&2
  echo "  cd ../llama.cpp && cmake --build build --config Release --target llama-tokenize -j" >&2
  exit 2
fi

# The 20 ISA opcode/envelope tokens (v1.0).
OPCODES=(
  "<|read|>"
  "<|write|>"
  "<|call|>"
  "<|/call|>"
  "<|yield|>"
  "<|fork|>"
  "<|wait|>"
  "<|loop|>"
  "<|break|>"
  "<|halt|>"
  "<|think|>"
  "<|/think|>"
  "<|commit|>"
  "<|fault|>"
  "<|policy|>"
  "<|state|>"
  "<|/state|>"
  "<|result|>"
  "<|/result|>"
  "<|ack|>"
)

count_tokens() {
  local vocab="$1" prompt="$2"
  local out
  out=$("$TOKENIZE" -m "$vocab" -p "$prompt" --no-bos --log-disable --show-count --ids 2>/dev/null \
        | grep -E '^Total number of tokens:' | awk '{print $NF}')
  if [ -z "$out" ]; then
    echo "?"
  else
    echo "$out"
  fi
}

# ─── Validation mode ─────────────────────────────────────────────────────────

if [ -n "$VALIDATE_MODEL" ]; then
  if [ ! -f "$VALIDATE_MODEL" ]; then
    echo "error: model not found: $VALIDATE_MODEL" >&2
    exit 2
  fi

  echo "Validating ISA token encoding in: $VALIDATE_MODEL"
  echo "Using tokenizer: $(basename "$TOKENIZE")"
  echo
  printf "%-18s %-8s %s\n" "Token" "Count" "Status"
  printf "%-18s %-8s %s\n" "-----" "-----" "------"

  FAILURES=0
  MAX_VARIANCE=0
  for op in "${OPCODES[@]}"; do
    n=$(count_tokens "$VALIDATE_MODEL" "$op")
    if [ "$n" = "1" ]; then
      status="OK"
    elif [ "$n" = "?" ]; then
      status="ERROR"
      FAILURES=$((FAILURES + 1))
    else
      status="FAIL ($n tokens)"
      FAILURES=$((FAILURES + 1))
      if [ "$n" -gt "$MAX_VARIANCE" ] 2>/dev/null; then
        MAX_VARIANCE="$n"
      fi
    fi
    printf "%-18s %-8s %s\n" "$op" "$n" "$status"
  done

  echo
  if [ "$FAILURES" -eq 0 ]; then
    echo "PASSED: all ${#OPCODES[@]} ISA tokens are single-token."
    echo "Token variance: 0% (uniform latency achieved)"
    exit 0
  else
    echo "FAILED: $FAILURES/${#OPCODES[@]} tokens are not single-token."
    if [ "$MAX_VARIANCE" -gt 0 ]; then
      echo "Max token count: $MAX_VARIANCE (target: 1)"
    fi
    exit 1
  fi
fi

# ─── Report mode (default) ───────────────────────────────────────────────────

QWEN_VOCAB="$LLAMA_DIR/models/ggml-vocab-qwen2.gguf"
GEMMA_VOCAB="$LLAMA_DIR/models/ggml-vocab-gemma-4.gguf"
for v in "$QWEN_VOCAB" "$GEMMA_VOCAB"; do
  if [ ! -f "$v" ]; then
    echo "error: missing vocab file: $v" >&2
    exit 2
  fi
done

SAMPLES=(
  "<|read|>fd=3 len=128"
  "<|write|>fd=1 {\"msg\":\"ready\"}"
  "<|call|>roclaw.forward {\"left\":150,\"right\":150} <|/call|>"
  "<|loop|>goal=navigate_to_kitchen"
  "<|break|>"
  "<|halt|>status=success"
  "<|result|>\"ok\"<|/result|>"
  "<|state|>{\"loop_depth\":1}<|/state|>"
)

{
  echo "# ISA Tokenization Report"
  echo
  echo "*Auto-generated by \`scripts/check_tokenizer.sh\`.*"
  echo
  echo "## Per-opcode token count (bootstrap kernels)"
  echo
  echo "| Opcode | Qwen 2/3 | Gemma 4 | Parity | Target (v1.0) |"
  echo "|---|---:|---:|:---:|:---:|"
  for op in "${OPCODES[@]}"; do
    qn=$(count_tokens "$QWEN_VOCAB" "$op")
    gn=$(count_tokens "$GEMMA_VOCAB" "$op")
    if [ "$qn" = "$gn" ]; then parity="="; else parity="!="; fi
    printf '| `%s` | %s | %s | %s | 1 |\n' "${op//|/\\|}" "$qn" "$gn" "$parity"
  done
  echo
  echo "## Per-statement token count"
  echo
  echo "| Statement | Qwen 2/3 | Gemma 4 |"
  echo "|---|---:|---:|"
  for s in "${SAMPLES[@]}"; do
    qn=$(count_tokens "$QWEN_VOCAB" "$s")
    gn=$(count_tokens "$GEMMA_VOCAB" "$s")
    disp="${s//|/\\|}"
    printf '| `%s` | %s | %s |\n' "$disp" "$qn" "$gn"
  done
  echo
  echo "## Validation"
  echo
  echo '```bash'
  echo 'bash scripts/check_tokenizer.sh --model path/to/finetuned.gguf'
  echo '```'
  echo
  echo "CI gate: exits 0 only if ALL ${#OPCODES[@]} ISA tokens are single-token."
} > "$REPORT"

echo "wrote $REPORT"
